# MicroDrop 2 Conda environment definition
# ----------------------------------------
#
# See `README.md` for more information.
name: microdrop-exe
channels:
  - conda-forge
  - sci-bots/label/py2exe
  - alexsk
  - sci-bots/label/microdrop-2-plugins
  - sci-bots/label/dropbot
  - sci-bots/label/microdrop-2
  - microdrop-plugins
  - dropbot
  - sci-bots
  - wheeler-microfluidics
  - defaults
dependencies:
  - microdrop
  - microdrop.dmf-device-ui-plugin
  - microdrop.dropbot-plugin
  - microdrop.droplet-planning-plugin
  - microdrop.mr-box-plugin>=0.25.1
  - microdrop.step-label-plugin
  - microdrop.user-prompt-plugin
  - microdrop.joypad-control-plugin
  - microdrop-plugin-manager
  - cycler=0.10=1 # See https://github.com/sci-bots/cycler-recipe
  - py2exe=0.6.9=py27
  - py2exe-helpers>=0.2.8
  - pydash<5.0
  - mr-box-peripheral-board>=0.31.2
  - mr-box-peripheral-board-dev>=0.31.2
  - openpyxl-helpers>=0.6.1
