name: microdrop-exe
channels:
  - dropbot
  - sci-bots/label/py2exe
  - sci-bots/label/microdrop-2-plugins
  - sci-bots/label/microdrop-2
  - sci-bots
  - wheeler-microfluidics
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - appdirs=1.4.3=py_0
  - arduino-fast-digital=v0.1=0
  - arduino-helpers=0.4=py27_0
  - arduino-linked-list=1.2.3=1
  - arduino-rpc=1.10.0=0
  - arduino-slow-soft-i2c-master=1.0.1.0=0
  - arduino-slow-soft-wire=1.0.1.0=0
  - arrow=0.8.0=py27_0
  - asn1crypto=0.22.0=py27_0
  - asyncserial=0.2=py27_0+git969359e
  - attrs=18.2.0=py_0
  - babel=2.6.0=py_1
  - backports.shutil_get_terminal_size=1.0.0=py_3
  - backports=1.0=py27_1
  - backports_abc=0.5=py27_0
  - base-node-rpc=0.41.1=py27_0
  - base-node=0.10.1=py27_0
  - blas=1.0=mkl
  - bleach=2.0.0=py27_0
  - blinker=1.4=py_0
  - bottle=0.12.9=py27_0
  - bzip2=1.0.6=vc9_1
  - ca-certificates=2018.4.16=0
  - cairo-helpers=0.2.post1=0
  - certifi=2018.4.16=py27_0
  - cffi=1.11.2=py27_0
  - chardet=3.0.4=py27_0
  - clang-helpers=0.5=py27_0
  - clang=3.9.0=0
  - cogapp=2.5.1=py27_0
  - colorama=0.3.9=py27_0
  - conda-env=2.6.0=0
  - conda-helpers=0.12.3=py27_0
  - conda=4.3.32=py27_0
  - configobj=4.7.2=py27_0
  - configparser=3.5.0=py27_0
  - cryptography=2.1.4=py27_0
  - cycler=0.10=1
  - debounce=0.1=py27_0
  - decorator=4.1.2=py27_0
  - dmf-device-ui=0.10=0
  - docutils=0.14=py27_0
  - dropbot=1.44=py27_0
  - droplet-planning=0.2.post1=0
  - entrypoints=0.2.3=py27_1
  - enum34=1.1.6=py27_1
  - et_xmlfile=1.0.1=py27_0
  - fastcache=1.0.2=py27_0
  - flatland-fork=0.5=0
  - funcsigs=1.0.2=py_3
  - futures=3.2.0=py27_0
  - geo_util=0.3=0
  - git=2.14.2=3
  - git_helpers=0.2=0
  - gitdb2=2.0.2=py27_0
  - gitpython=2.1.7=py27_0
  - hdf5=1.10.1=vc9_1
  - html5lib=1.0.1=py_0
  - icu=58.2=vc9_0
  - idna=2.6=py27_1
  - imagesize=1.1.0=py_0
  - ipaddress=1.0.18=py27_0
  - ipykernel=4.8.2=py27_0
  - ipython=5.5.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - ipywidgets=7.1.0=py27_0
  - jdcal=1.2=py27_0
  - jinja2=2.10=py27_0
  - jpeg=9b=vc9_2
  - json-tricks=3.8.0=py27_0
  - jsonschema=2.5.1=py27_0
  - jupyter=1.0.0=py27_0
  - jupyter_client=5.2.1=py27_0
  - jupyter_console=5.2.0=py27_0
  - jupyter_core=4.4.0=py_0
  - libpng=1.6.34=vc9_0
  - lockfile=0.12.2=py27_0
  - logging-helpers=0.4=py_0
  - lxml=4.1.1.post1=0
  - markupsafe=1.0=py27_0
  - matplotlib=2.0.2=np111py27_gtk2_3
  - menuinst=1.4.8=py27_0
  - microdrop-device-converter=0.1.post5=0
  - microdrop-launcher=0.7.12=0
  - microdrop-plugin-manager=0.25.1=0
  - microdrop-plugin-template=1.3=0
  - microdrop.dmf-device-ui-plugin=2.6=0
  - microdrop.dropbot-plugin=2.23=0
  - microdrop.droplet-planning-plugin=2.3.1=0
  - microdrop.step-label-plugin=2.2.2=0
  - microdrop.user-prompt-plugin=2.3.1=0
  - microdrop=2.19=0
  - mingw=4.7=1
  - mistune=0.8.3=py_0
  - mkl=2017.0.1=0
  - more-itertools=4.2.0=py_0
  - mpmath=1.0.0=py_0
  - nadamq=0.14=py27_0
  - nanopb-helpers=0.7=py27_0
  - nanopb=0.3.7=py27_0
  - natsort=4.0.4=py27_0
  - nbconvert=5.4.1=py_2
  - nbformat=4.4.0=py27_0
  - networkx=2.0=py27_1
  - notebook=5.2.2=py27_1
  - numexpr=2.6.4=py27_0
  - numpy=1.11.3=py27_0
  - opencv-helpers=0.1.post1=0
  - openpyxl=2.5.0b1=py27_0
  - openssl=1.0.2o=vc9_0
  - or-event=0.1.0=py27_0
  - packaging=19.0=py_0
  - paho-mqtt-helpers=0.1=py27_0
  - paho-mqtt=1.2.3=py27_0
  - pandas=0.22.0=py27_0
  - pandoc=2.1=0
  - pandocfilters=1.4.1=py27_0
  - path_helpers=0.8=py27_0
  - pathlib2=2.3.0=py27_0
  - paver=1.2.4=py_1
  - pickleshare=0.7.4=py27_0
  - pint=0.8.1=py27_0
  - pip-helpers=0.6.post3=0
  - pip=9.0.1=py27_1
  - platformio-helpers=0.4.0=py27_0
  - platformio-platform-atmelavr=1.4.5=0
  - platformio-platform-teensy=2.0.0=0
  - platformio-tool-avrdude=1.60300.2=0
  - platformio-tool-scons=3.20501.2=0
  - platformio-tool-teensy=1.21.0=1
  - platformio=3.4.1=py27_1
  - pluggy=0.6.0=py_0
  - progressbar2=3.10.1=py27_0
  - prompt_toolkit=1.0.15=py27_0
  - protobuf=3.5.1=py27_vc9_3
  - protoc=3.1.0=0
  - psutil=5.4.0=py27_0
  - py=1.7.0=py_0
  - pycairo-gtk2=0.1.0=py27_1
  - pycosat=0.6.3=py27_0
  - pycparser=2.18=py27_0
  - pydash=4.7.3=py_0
  - pygio2=0.1.0=py27_1
  - pyglib2=0.1.0=py27_1
  - pygments=2.2.0=py27_0
  - pygst-0.10=0.1.post2=0
  - pygst_utils=0.3.4=1
  - pygtk2=0.1.0=py27_3
  - pyopenssl=17.2.0=py27_0
  - pyparsing=2.2.0=py27_0
  - pyqt=5.6.0=py27_5
  - pyserial=3.4=py27_0
  - pysocks=1.6.8=py27_1
  - pytables=3.4.2=py27_7
  - pytest-runner=4.4=py_0
  - pytest=3.5.0=py27_0
  - python-dateutil=2.6.1=py27_0
  - python-utils=2.0.0=0
  - python=2.7.14=4
  - pytz=2017.3=py_2
  - pyutilib.component.config=3.8=0
  - pyutilib.component.core=4.6.4=0
  - pyutilib.component.loader=3.4.1=0
  - pywin32=221=py27_0
  - pyyaml=3.12=py27_1
  - pyzmq=16.0.2=py27_3
  - qt=5.6.2=vc9_1
  - qtconsole=4.3.1=py27_0
  - rename-package-files=0.1.post1=0
  - requests=2.18.4=py27_1
  - scandir=1.7=py27_0
  - scipy=0.19.0=np111py27_0
  - semantic_version=2.6.0=py27_0
  - serial-device=0.9=py27_0
  - setuptools=38.4.0=py27_0
  - simplegeneric=0.8.1=py27_0
  - singledispatch=3.4.0.3=py27_0
  - sip=4.18=py27_1
  - six=1.11.0=py27_1
  - smmap2=2.0.3=py27_0
  - snowballstemmer=1.2.1=py_1
  - sphinx=1.7.5=py27_0
  - sphinxcontrib-websupport=1.1.0=py_1
  - sqlite=3.13.0=vc9_1
  - ssl_match_hostname=3.5.0.1=py27_1
  - svg-model=0.9.1=0
  - svgwrite=1.1.8=0
  - sympy=1.1.1=py27_0
  - teensy-minimal-rpc=0.6.1=py27_0
  - testpath=0.3.1=py27_0
  - tornado=4.5.3=py27_0
  - traitlets=4.3.2=py27_0
  - trollius=2.1=py27_0
  - typing=3.6.4=py27_0
  - urllib3=1.22=py27_0
  - vc=9=0
  - versioneer=0.18=py27_0
  - virtualenv=15.1.0=py27_0
  - vs2008_runtime=9.0.30729.6161=0
  - wcwidth=0.1.7=py27_0
  - webencodings=0.5=py27_0
  - wheel=0.30.0=py27_2
  - wheeler.pygtkhelpers=0.20=0
  - widgetsnbextension=3.2.1=py27_1
  - win_inet_pton=1.0.1=py27_1
  - win_unicode_console=0.5=py27_0
  - wincertstore=0.2=py27_0
  - yaml=0.1.7=vc9_0
  - zlib=1.2.11=vc9_0
  - zmq-plugin=0.3=0
  - py2exe-helpers=0.2.5=0
  - py2exe=0.6.9=py27
  - ruamel.ordereddict=0.4.13=py27_0
  - ruamel.yaml=0.15.37=py27_0
  - jsonpickle=0.9.6=py_1
  - asyncio-helpers=0.2.1=0
  - pymunk=4.0.0=0
